import os

import bpy
from bpy_extras.io_utils import axis_conversion
from mathutils import Matrix


OUT_PATH = r"C:\Models\png\PATH.obj"
SUMMARY_PATH = r"C:\Models\png\PATH.export.txt"
OBJECT_NAMES = ("trilha_1", "trilha_2", "trilha_3")
EXPORT_FORWARD = "Z"
EXPORT_UP = "-Y"
GLOBAL_SCALE = 10.0


def build_export_matrix():
    return axis_conversion(
        to_forward=EXPORT_FORWARD,
        to_up=EXPORT_UP).to_4x4() @ Matrix.Scale(GLOBAL_SCALE, 4)


def edge_key(a, b):
    return (a, b) if a < b else (b, a)


def connected_components(adjacency):
    remaining = {index for index, neighbors in adjacency.items() if neighbors}
    components = []
    while remaining:
        seed = next(iter(remaining))
        stack = [seed]
        component = []
        remaining.remove(seed)
        while stack:
            current = stack.pop()
            component.append(current)
            for neighbor in adjacency[current]:
                if neighbor in remaining:
                    remaining.remove(neighbor)
                    stack.append(neighbor)
        components.append(component)
    return components


def order_polyline_from_mesh(mesh, object_name):
    adjacency = {index: [] for index in range(len(mesh.vertices))}
    for edge in mesh.edges:
        v0, v1 = edge.vertices[:]
        adjacency[v0].append(v1)
        adjacency[v1].append(v0)

    active = [index for index, neighbors in adjacency.items() if neighbors]
    if not active:
        raise ValueError(f"{object_name}: nenhuma aresta encontrada")

    branched = [index for index, neighbors in adjacency.items() if len(neighbors) > 2]
    if branched:
        raise ValueError(
            f"{object_name}: trilha ramificada; vertices com grau > 2: {branched[:8]}")

    components = connected_components(adjacency)
    if len(components) != 1:
        raise ValueError(
            f"{object_name}: esperado 1 componente conectado, encontrados {len(components)}")

    endpoints = [index for index in active if len(adjacency[index]) == 1]
    closed_loop = len(endpoints) == 0
    if not closed_loop and len(endpoints) != 2:
        raise ValueError(
            f"{object_name}: esperado 2 extremidades, encontradas {len(endpoints)}")

    start = min(endpoints) if endpoints else min(active)
    ordered = [start]
    used_edges = set()
    previous = None
    current = start

    while True:
        candidates = []
        for neighbor in adjacency[current]:
            key = edge_key(current, neighbor)
            if key in used_edges:
                continue
            candidates.append(neighbor)

        if not candidates:
            break

        if previous is not None and len(candidates) > 1:
            preferred = [neighbor for neighbor in candidates if neighbor != previous]
            if preferred:
                candidates = preferred

        nxt = candidates[0]
        used_edges.add(edge_key(current, nxt))
        if closed_loop and nxt == start:
            break

        ordered.append(nxt)
        previous, current = current, nxt

    if len(used_edges) != len(mesh.edges):
        raise ValueError(
            f"{object_name}: nem todas as arestas foram percorridas "
            f"({len(used_edges)}/{len(mesh.edges)})")

    return ordered


def gather_object_points(obj, depsgraph, export_matrix):
    eval_obj = obj.evaluated_get(depsgraph)
    mesh = eval_obj.to_mesh()
    if mesh is None:
        raise ValueError(f"{obj.name}: falha ao gerar mesh avaliada")

    try:
        if len(mesh.vertices) == 0:
            raise ValueError(f"{obj.name}: nenhum vertice encontrado")

        ordered_indices = order_polyline_from_mesh(mesh, obj.name)
        world_matrix = eval_obj.matrix_world.copy()

        points = []
        for vertex_index in ordered_indices:
            co_world = world_matrix @ mesh.vertices[vertex_index].co
            co_export = export_matrix @ co_world.to_4d()
            points.append((co_export.x, co_export.y, co_export.z))

        if len(points) < 2:
            raise ValueError(f"{obj.name}: trilha com menos de 2 pontos")

        return points
    finally:
        eval_obj.to_mesh_clear()


def write_path_obj(output_path, lines):
    out_dir = os.path.dirname(output_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    next_index = 1
    summary_lines = []

    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("# PATH.obj generated by blender_export_path_obj.py\n")
        handle.write("# Objects are exported as OBJ polylines for PATH.NYA conversion.\n")

        for object_name, points in lines:
            handle.write(f"o {object_name}\n")
            start_index = next_index

            for x, y, z in points:
                handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
                next_index += 1

            indices = " ".join(str(index) for index in range(start_index, next_index))
            handle.write(f"l {indices}\n")

            summary_lines.append(f"{object_name}: {len(points)} pontos")

    return summary_lines


def main():
    depsgraph = bpy.context.evaluated_depsgraph_get()
    export_matrix = build_export_matrix()

    exported_lines = []
    for object_name in OBJECT_NAMES:
        obj = bpy.data.objects.get(object_name)
        if obj is None:
            raise ValueError(f"Objeto nao encontrado: {object_name}")

        points = gather_object_points(obj, depsgraph, export_matrix)
        exported_lines.append((object_name, points))

    summary_lines = write_path_obj(OUT_PATH, exported_lines)

    summary_dir = os.path.dirname(SUMMARY_PATH)
    if summary_dir:
        os.makedirs(summary_dir, exist_ok=True)
    with open(SUMMARY_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(summary_lines))
        handle.write("\n")

    print(f"Exportado: {OUT_PATH}")
    print(f"Resumo: {SUMMARY_PATH}")
    for line in summary_lines:
        print(f"  {line}")


if __name__ == "__main__":
    main()
